```{r}
#| label: setup-global
#| include: false

source(file.path("R", "paths.R"))
source(project_path("R", "00-setup.R"))
source(project_path("R", "01-functions.R"))
```

{{< include Portada.qmd >}}

\cleardoublepage

\pagenumbering{roman}
\setcounter{page}{1}
\pagestyle{fancy}

{{< include preambulo/dedicatoria.qmd >}}
{{< include preambulo/agradecimientos.qmd >}}
{{< include preambulo/resumen.qmd >}}
{{< include preambulo/resumo.qmd >}}
{{< include preambulo/abstract.qmd >}}

\cleardoublepage
\renewcommand{\contentsname}{ÍNDICE}
\setcounter{tocdepth}{1}
\tableofcontents
\cleardoublepage
\renewcommand{\listtablename}{Índice de tablas}
\listoftables
\cleardoublepage
\renewcommand{\listfigurename}{Índice de figuras}
\listoffigures
\cleardoublepage

{{< include preambulo/siglas.qmd >}}

\cleardoublepage
\pagenumbering{arabic}
\setcounter{page}{1}
\pagestyle{fancy}

{{< include capitulos/CapituloI.qmd >}}

\part{MARCO CONCEPTUAL Y REVISIÓN DE LA LITERATURA}

{{< include capitulos/CapituloII.qmd >}}
{{< include capitulos/CapituloIII.qmd >}}
{{< include capitulos/CapituloIV.qmd >}}

\part{PRODUCTIVIDAD AGRARIA Y TENENCIA DE LA TIERRA EN EL ECUADOR: ANÁLISIS ESTADÍSTICO Y ECONOMÉTRICO}

{{< include capitulos/CapituloV.qmd >}}
{{< include capitulos/CapituloVI.qmd >}}
{{< include capitulos/CapituloVII.qmd >}}
{{< include capitulos/CapituloVIII.qmd >}}

# Bibliografía {.unnumbered}

\markboth{Bibliografía}{Bibliografía}

::: {#refs}
:::

\cleardoublepage

\phantomsection
\chapter*{ANEXOS}
\addcontentsline{toc}{chapter}{ANEXOS}
\cleardoublepage
\addtocontents{toc}{\protect\renewcommand{\protect\cftchappresnum}{Anexo~}\protect\setlength{\protect\cftchapnumwidth}{7em}}
\appendix
\renewcommand{\appendixname}{Anexo}
\renewcommand{\chaptername}{Anexo}

{{< include anexos/AnexoI_Precios.qmd >}}

\cleardoublepage

{{< include anexos/AnexoII_Construccion_Base.qmd >}}


